INSERT INTO tags (name)
VALUES ('LTWD - Long time with defender'),
       ('BL/CH - Block Charge'),
       ('T&D - Time & Distance'),
       ('OFB - Off the Ball'),
       ('UF - Unsportsmanlike'),
       ('FK - Fake'),
       ('PCE - Primary coverage'),
       ('EOG - End Of the Game'),
       ('EOQ - End Of the Quarter'),
       ('EPL - Edge of the Play'),
       ('WA - Working area'),
       ('PRO - Preventative Officiating'),
       ('Check IN'),
       ('Check OUT'),
       ('OOB - Out-of-Bounds'),
       ('SCE - Secondary Coverage'),
       ('FAOS - Fouled in Act of Shooting (AOS)'),
       ('FNAOS - Foul not in Act of shooting'),
       ('AMI - Active mindset'),
       ('AOR - Area of responsibility'),
       ('SCC - Shot Clock control'),
       ('FAC - Fantasy call');
